### ISSUE TITLE
オプション画面のラベルが文字化けしています

### ISSUE THREAD

**Issue by htomine** [mizoguche/my-qiita-team-today#1]
![image](https://cloud.githubusercontent.com/assets/732828/10986566/7d3c580a-846e-11e5-8722-ddc8aa2fba4b.png)

Mac OSX 10.11 / Google Chrome バージョン 46.0.2490.80 (64-bit)

**Comment by mizoguche** [comment]
ご報告ありがとうございます。

こちらの環境では再現できなかったのですが、たぶん文字コードを指定してなかったのが原因だと思われますので修正しました。

**Comment by htomine** [comment]
@mizoguche ありがとうございます！
